// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user.proto

package user_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ModifySegmentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModifySegmentsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModifySegmentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModifySegmentsRequestMultiError, or nil if none found.
func (m *ModifySegmentsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ModifySegmentsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := ModifySegmentsRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ModifySegmentsRequestMultiError(errors)
	}

	return nil
}

// ModifySegmentsRequestMultiError is an error wrapping multiple validation
// errors returned by ModifySegmentsRequest.ValidateAll() if the designated
// constraints aren't met.
type ModifySegmentsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModifySegmentsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModifySegmentsRequestMultiError) AllErrors() []error { return m }

// ModifySegmentsRequestValidationError is the validation error returned by
// ModifySegmentsRequest.Validate if the designated constraints aren't met.
type ModifySegmentsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModifySegmentsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModifySegmentsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModifySegmentsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModifySegmentsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModifySegmentsRequestValidationError) ErrorName() string {
	return "ModifySegmentsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ModifySegmentsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModifySegmentsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModifySegmentsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModifySegmentsRequestValidationError{}

// Validate checks the field values on GetSegmentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSegmentsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSegmentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSegmentsRequestMultiError, or nil if none found.
func (m *GetSegmentsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSegmentsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := GetSegmentsRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetSegmentsRequestMultiError(errors)
	}

	return nil
}

// GetSegmentsRequestMultiError is an error wrapping multiple validation errors
// returned by GetSegmentsRequest.ValidateAll() if the designated constraints
// aren't met.
type GetSegmentsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSegmentsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSegmentsRequestMultiError) AllErrors() []error { return m }

// GetSegmentsRequestValidationError is the validation error returned by
// GetSegmentsRequest.Validate if the designated constraints aren't met.
type GetSegmentsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSegmentsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSegmentsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSegmentsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSegmentsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSegmentsRequestValidationError) ErrorName() string {
	return "GetSegmentsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSegmentsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSegmentsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSegmentsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSegmentsRequestValidationError{}

// Validate checks the field values on GetSegmentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSegmentsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSegmentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSegmentsResponseMultiError, or nil if none found.
func (m *GetSegmentsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSegmentsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetSegmentsResponseMultiError(errors)
	}

	return nil
}

// GetSegmentsResponseMultiError is an error wrapping multiple validation
// errors returned by GetSegmentsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetSegmentsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSegmentsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSegmentsResponseMultiError) AllErrors() []error { return m }

// GetSegmentsResponseValidationError is the validation error returned by
// GetSegmentsResponse.Validate if the designated constraints aren't met.
type GetSegmentsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSegmentsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSegmentsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSegmentsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSegmentsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSegmentsResponseValidationError) ErrorName() string {
	return "GetSegmentsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetSegmentsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSegmentsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSegmentsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSegmentsResponseValidationError{}
