// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: user.proto

package user_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserV1ServiceClient is the client API for UserV1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserV1ServiceClient interface {
	ModifySegments(ctx context.Context, in *ModifySegmentsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetSegments(ctx context.Context, in *GetSegmentsRequest, opts ...grpc.CallOption) (*GetSegmentsResponse, error)
	SetExpireTime(ctx context.Context, in *SetExpireTimeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
	RemoveUser(ctx context.Context, in *RemoveUsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUserHistoryCsv(ctx context.Context, in *GetUserHistoryCsvRequest, opts ...grpc.CallOption) (*GetUserHistoryCsvResponse, error)
}

type userV1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserV1ServiceClient(cc grpc.ClientConnInterface) UserV1ServiceClient {
	return &userV1ServiceClient{cc}
}

func (c *userV1ServiceClient) ModifySegments(ctx context.Context, in *ModifySegmentsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/segment.service.api.UserV1Service/ModifySegments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userV1ServiceClient) GetSegments(ctx context.Context, in *GetSegmentsRequest, opts ...grpc.CallOption) (*GetSegmentsResponse, error) {
	out := new(GetSegmentsResponse)
	err := c.cc.Invoke(ctx, "/segment.service.api.UserV1Service/GetSegments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userV1ServiceClient) SetExpireTime(ctx context.Context, in *SetExpireTimeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/segment.service.api.UserV1Service/SetExpireTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userV1ServiceClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, "/segment.service.api.UserV1Service/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userV1ServiceClient) RemoveUser(ctx context.Context, in *RemoveUsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/segment.service.api.UserV1Service/RemoveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userV1ServiceClient) GetUserHistoryCsv(ctx context.Context, in *GetUserHistoryCsvRequest, opts ...grpc.CallOption) (*GetUserHistoryCsvResponse, error) {
	out := new(GetUserHistoryCsvResponse)
	err := c.cc.Invoke(ctx, "/segment.service.api.UserV1Service/GetUserHistoryCsv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserV1ServiceServer is the server API for UserV1Service service.
// All implementations must embed UnimplementedUserV1ServiceServer
// for forward compatibility
type UserV1ServiceServer interface {
	ModifySegments(context.Context, *ModifySegmentsRequest) (*emptypb.Empty, error)
	GetSegments(context.Context, *GetSegmentsRequest) (*GetSegmentsResponse, error)
	SetExpireTime(context.Context, *SetExpireTimeRequest) (*emptypb.Empty, error)
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
	RemoveUser(context.Context, *RemoveUsertRequest) (*emptypb.Empty, error)
	GetUserHistoryCsv(context.Context, *GetUserHistoryCsvRequest) (*GetUserHistoryCsvResponse, error)
	mustEmbedUnimplementedUserV1ServiceServer()
}

// UnimplementedUserV1ServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserV1ServiceServer struct {
}

func (UnimplementedUserV1ServiceServer) ModifySegments(context.Context, *ModifySegmentsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifySegments not implemented")
}
func (UnimplementedUserV1ServiceServer) GetSegments(context.Context, *GetSegmentsRequest) (*GetSegmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSegments not implemented")
}
func (UnimplementedUserV1ServiceServer) SetExpireTime(context.Context, *SetExpireTimeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetExpireTime not implemented")
}
func (UnimplementedUserV1ServiceServer) AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedUserV1ServiceServer) RemoveUser(context.Context, *RemoveUsertRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUser not implemented")
}
func (UnimplementedUserV1ServiceServer) GetUserHistoryCsv(context.Context, *GetUserHistoryCsvRequest) (*GetUserHistoryCsvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserHistoryCsv not implemented")
}
func (UnimplementedUserV1ServiceServer) mustEmbedUnimplementedUserV1ServiceServer() {}

// UnsafeUserV1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserV1ServiceServer will
// result in compilation errors.
type UnsafeUserV1ServiceServer interface {
	mustEmbedUnimplementedUserV1ServiceServer()
}

func RegisterUserV1ServiceServer(s grpc.ServiceRegistrar, srv UserV1ServiceServer) {
	s.RegisterService(&UserV1Service_ServiceDesc, srv)
}

func _UserV1Service_ModifySegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifySegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserV1ServiceServer).ModifySegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/segment.service.api.UserV1Service/ModifySegments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserV1ServiceServer).ModifySegments(ctx, req.(*ModifySegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserV1Service_GetSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserV1ServiceServer).GetSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/segment.service.api.UserV1Service/GetSegments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserV1ServiceServer).GetSegments(ctx, req.(*GetSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserV1Service_SetExpireTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetExpireTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserV1ServiceServer).SetExpireTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/segment.service.api.UserV1Service/SetExpireTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserV1ServiceServer).SetExpireTime(ctx, req.(*SetExpireTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserV1Service_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserV1ServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/segment.service.api.UserV1Service/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserV1ServiceServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserV1Service_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserV1ServiceServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/segment.service.api.UserV1Service/RemoveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserV1ServiceServer).RemoveUser(ctx, req.(*RemoveUsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserV1Service_GetUserHistoryCsv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserHistoryCsvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserV1ServiceServer).GetUserHistoryCsv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/segment.service.api.UserV1Service/GetUserHistoryCsv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserV1ServiceServer).GetUserHistoryCsv(ctx, req.(*GetUserHistoryCsvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserV1Service_ServiceDesc is the grpc.ServiceDesc for UserV1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserV1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "segment.service.api.UserV1Service",
	HandlerType: (*UserV1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModifySegments",
			Handler:    _UserV1Service_ModifySegments_Handler,
		},
		{
			MethodName: "GetSegments",
			Handler:    _UserV1Service_GetSegments_Handler,
		},
		{
			MethodName: "SetExpireTime",
			Handler:    _UserV1Service_SetExpireTime_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _UserV1Service_AddUser_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _UserV1Service_RemoveUser_Handler,
		},
		{
			MethodName: "GetUserHistoryCsv",
			Handler:    _UserV1Service_GetUserHistoryCsv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
