version: "3"

volumes:
  postgres-volume:

services:
  postgres:
    build: .database/
    image: postgres:14-alpine3.15
    container_name: 'avito_postgres'
    environment:
      - "POSTGRES_DB=segments_db"
      - "POSTGRES_PASSWORD=avito_pass"
      - "POSTGRES_USER=postgres"
      - "PGDATA=/var/lib/postgresql/data/notification"
    volumes: 
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"